### ISSUE TITLE
Spike: Google Calendar Integration

### ISSUE THREAD

**Issue by PokeJofeJr4th** [rit-sse/WebsiteTheSSEquel#163]
# Template Instructions

Use this template to create a new Spike item.
# Google Calendar Integration

## Problem Statement

We want to add integrations between our website and Google Calendar.

## Goal

We want to learn how to use a library or API to handle Google Calendar events.

## Hypothesis

I expect there is a library or API we can use to integrate with google calendar. I expect we will be able to use this with nextauth.

**Comment by rtyocum** [comment]
Are we editing events on the website or just reading? Google calendar is easy for read access, requires oAuth, or a service account for the google calendar api to write to it

**Comment by 2nPlusOne** [comment]
> Are we editing events on the website or just reading? Google calendar is easy for read access, requires oAuth, or a service account for the google calendar api to write to it

Double check the vision document for the MVP requirements. The SSEs google account with our calendar has what we need, but we need to think about best practices for secrets management when using that.

**Comment by 2nPlusOne** [comment]
I don’t have the link on hand right now but you can find it in the bookmarks for the technology channel in slack.
