### ISSUE TITLE
Story: Leadership About Page

### ISSUE THREAD

**Issue by 2nPlusOne** [rit-sse/WebsiteTheSSEquel#32]
# Leadership About Page

**User Story:**

As a visitor, I want to visit the Leadership page so that I can learn about present and past leadership teams.

**Associated Epic:** [Link to Epic](https://github.com/rit-sse/WebsiteTheSSEquel/issues/27)

## Definition of Done

- [x] Acceptance criteria defined
- [x] Solution tasks specified
- [x] Feature branch created
- [ ] Unit tests written (on API code only for now)
- [ ] Solution passes full suite of unit tests
- [x] Design documents updated if needed
- [x] Pull request created
- [ ] Code is reviewed
- [ ] Code is merged to `main` branch
- [ ] Tests pass on CI
- [ ] Deployed to staging environment
- [x] Acceptance criteria is met

## Acceptance Criteria

- [ ] Given that the user visits the website, when they click on the "Leadership" link in the navbar, then they should be directed to the Leadership Page.
- [x] Given the Leadership Page is loaded, when a user scrolls through the page, then they should see information about the Primary Officers.
- [ ] Given the Leadership Page is loaded, when a user interacts with the page, then they should be able to access information about the Committee Heads.

## Depends on

- [] API route to access officer data from the database

## Solution Tasks

- [x] Define the user story, acceptance criteria, and tasks for Leadership Page integration.
- [x] Create a feature branch for Leadership Page integration.
- [ ] Ensure the solution passes the full suite of unit tests.
- [x] Update design documents if needed.
- [x] Create the pull request for Leadership Page integration.
- [ ] Review and merge the code into the `main` branch.
- [ ] Ensure tests pass on CI.
- [ ] Deploy to the staging environment.
- [x] Meet the defined acceptance criteria.

**Comment by 2nPlusOne** [comment]
@ntr0pie When you finish this make sure to move it into "in review", and create your pull request. Before creating the PR, make sure you've merged main back into your branch and integrated the new color theme with semantic color names. If  you'd like help with any of these, let me or Raynard know. 

Also, please make sure to include a screenshot of the feature on the PR, so we can all see the way it looks! 💯

**Comment by ntr0pie** [comment]
@2nPlusOne 
All set. 
Moved it to "in review"
A [pull request](https://github.com/rit-sse/WebsiteTheSSEquel/pull/63) is in place too.
